# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_is_public', models.BooleanField(default=True)),
                ('town', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('phone_is_public', models.BooleanField(default=True)),
                ('street_address', models.TextField(blank=True)),
                ('street_address_is_public', models.BooleanField(default=True)),
                ('mailing_address', models.TextField(blank=True)),
                ('mailing_address_is_public', models.BooleanField(default=True)),
                ('about_me', models.TextField(blank=True)),
                ('include_in_member_profiles', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
