# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seednetwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='town',
        ),
    ]
