# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seednetwork', '0003_add_memberinfo_usda'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
