# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('show_on_seed_edit', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(blank=True, max_length=150)),
                ('crop_type', models.CharField(blank=True, max_length=150)),
                ('seed_variety', models.CharField(blank=True, max_length=150)),
                ('seed_description', models.TextField(blank=True)),
                ('enough_to_share', models.BooleanField(default=False)),
                ('year', models.CharField(blank=True, max_length=150)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='seed',
            field=models.ManyToManyField(blank=True, to='seedlibrary.Seed'),
        ),
    ]
