# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlibrary', '0002_auto_20170219_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedview',
            old_name='external_field',
            new_name='external_url',
        ),
        migrations.AddField(
            model_name='extendedview',
            name='grain_subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
