# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-22 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlibrary', '0003_extendedview_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedview',
            name='days_to_maturity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='lodging_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
