# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlibrary', '0004_fix_integernulls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedview',
            old_name='plant_timing',
            new_name='growth_habit',
        ),
        migrations.RenameField(
            model_name='extendedview',
            old_name='breed',
            new_name='improvement_status',
        ),
        migrations.RenameField(
            model_name='extendedview',
            old_name='other_traits',
            new_name='other_uses',
        ),
        migrations.RemoveField(
            model_name='extendedview',
            name='grain_subcategory',
        ),
        migrations.RemoveField(
            model_name='extendedview',
            name='lodging_percent',
        ),
        migrations.AddField(
            model_name='extendedview',
            name='additional_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedview',
            name='cultivation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seed',
            name='grain_subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='lodging',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
