# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlibrary', '006_char2textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedview',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
