# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-01 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlibrary', '0005_GRIN_and_addtl_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedview',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='cold_hardiness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='culinary_qualities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='cultivation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='disease',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='other_uses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extendedview',
            name='threshing',
            field=models.TextField(blank=True),
        ),
    ]
